# Generated by Django 2.2a1 on 2021-03-17 07:22

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_objectid', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('emailid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=50)),
                ('year_of_pass', models.IntegerField(default=-1)),
                ('course_type', models.CharField(max_length=50)),
                ('codechef_handle', models.CharField(max_length=50)),
                ('codeforces_handle', models.CharField(max_length=50)),
                ('atcoder_handle', models.CharField(max_length=50)),
                ('spoj_handle', models.CharField(max_length=50)),
                ('hackerrank_handle', models.CharField(max_length=50)),
                ('hackerearth_handle', models.CharField(max_length=50)),
                ('interviewbit_handle', models.CharField(max_length=50)),
                ('leetcode_handle', models.CharField(max_length=50)),
                ('github_handle', models.CharField(max_length=50)),
                ('linkedin_handle', models.CharField(max_length=50)),
            ],
        ),
    ]
